kind: pipeline
type: docker
name: build

steps:
- name: build
  image: golang:1.16
  volumes:
  - name: deps
    path: /go
  commands:
  - go get
  - go build

- name: test
  image: golang:1.16
  volumes:
  - name: deps
    path: /go
  environment:
    EVERY8D_BASEURL:
      from_secret: EVERY8D_BASEURL
    EVERY8D_USERNAME:
      from_secret: EVERY8D_USERNAME
    EVERY8D_PASSWORD:
      from_secret: EVERY8D_PASSWORD
    MITAKE_BASEURL:
      from_secret: MITAKE_BASEURL
    MITAKE_USERNAME:
      from_secret: MITAKE_USERNAME
    MITAKE_PASSWORD:
      from_secret: MITAKE_PASSWORD
  commands:
  - go test -v -cover -coverprofile coverage.out
  - go test -json > ${DRONE_REPO_NAME}/test-report.out

- name: code-analysis
  image: aosapps/drone-sonar-plugin
  settings:
    sonar_host:
      from_secret: sonar_host
    sonar_token:
      from_secret: sonar_token

volumes:
- name: deps
  temp: {}
