kind: pipeline
type: docker
name: build

steps:
- name: build
  image: golang:1.16
  volumes:
  - name: deps
    path: /go
  commands:
  - go get
  - go build
  - rm sms

- name: test
  image: golang:1.16
  volumes:
  - name: deps
    path: /go
  environment:
    SMS_PROVIDERS_0_ACCOUNT_USERNAME:
      from_secret: EVERY8D_USERNAME
    SMS_PROVIDERS_0_ACCOUNT_PASSWORD:
      from_secret: EVERY8D_PASSWORD
    SMS_PROVIDERS_1_ACCOUNT_USERNAME:
      from_secret: MITAKE_USERNAME
    SMS_PROVIDERS_1_ACCOUNT_PASSWORD:
      from_secret: MITAKE_PASSWORD
  commands:
  - go test -v -cover -coverprofile coverage.out
  - go test -json > test-report.out

- name: code-analysis
  image: sonarsource/sonar-scanner-cli
  environment:
    SONAR_HOST_URL:
      from_secret: SONAR_HOST_URL
    SONAR_LOGIN:
      from_secret: SONAR_LOGIN

volumes:
- name: deps
  temp: {}

trigger:
  event:
  - push
  - pull_request

---
kind: pipeline
type: docker
name: deploy-staging

steps:
- name: release
  image: plugins/docker
  settings:
    repo: tccgov.azurecr.io/tiwengo
    tags:
    - ${DOCKER_TAG}
    registry: tccgov.azurecr.io
    username: tccgov
    password: 
      from_secret: DOCKER_PASSWORD

- name: deploy
  image: appleboy/drone-ssh
  volumes:
  - name: ssh_key
    path: /root/.ssh
  settings:
    host: 10.78.0.1
    username: ar0660
    key_path: /root/.ssh/id_rsa
    script:
    - cd /home/ar0660/workspace
    - sudo docker-compose down
    - sudo docker-compose up -d

volumes:
- name: ssh_key
  host:
    path: /home/ar0660/.ssh

trigger:
  event:
  - promote
  target:
  - staging
