providers:
  every8d:
    type: every8d
    username: username
    password: password
    baseUrl: https://oms.every8d.com/API21/HTTP
    callbackUrl: https://api.linyc.idv.tw/notification/v1/providers/every8d/status/callback
  
  mitake:
    type: mitake
    username: username
    password: password
    baseUrl: https://smsapi.mitake.com.tw/api/mtk
    callbackUrl: https://api.linyc.idv.tw/notification/v1/providers/mitake/status/callback
